import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import store from "./reduxStore/store";
import { Provider } from "react-redux";
import MainLayout from "./_components/MainLayout";
import { Inter } from "next/font/google";

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
})

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="h-screen w-screen overflow-hidden flex justify-center">
                    <div className={`h-full w-full max-w-[1920px] ${inter.variable} font-sans`}>
                        <MainLayout>
                            {children}
                        </MainLayout>
                    </div>
                </div>
            </body>
        </html>
    );
}